= Importing

There are common features available when importing data into Redis (`db-import`, `faker`, `file-import`, `redis-import`, `snowflake-import`, `stream-import`).

== Redis Key

{project-title} offers two mechanisms to craft the Redis key:

=== Template Expression

This produces the key string using a https://docs.spring.io/spring-framework/reference/core/expressions/language-ref/templating.html[SpEL expression].

Template expressions allow mixing literal text with one or more evaluation blocks.
Each evaluation block is delimited with `#{ }` and within an evaluation block you can directly reference fields by their name, for example:

.Template Expression Example
[source,console,subs="verbatim,attributes"]
----
{app} file-import beers.json hset beer:#{id}
----

Here each key is constructed with the `beer:` prefix and suffixed with the value in the `id` field, producing keys `beer:123` `beer:494` etc.

=== Keyspace and Key Fields

This mechanism constructs keys using a keyspace string passed with `--keyspace` and key fields passed with `--key`, for example:

.Keyspace/Key Fields Example
[source,console,subs="verbatim,attributes"]
----
{app} file-import beers.json hset --keyspace beer --key id
----

== Processing

Processors allow you to create/update/delete fields using the Spring Expression Language ({link_spel}).

.Examples
`--proc field1="'foo'"`:: Generate a field named `field1` containing the string `foo`
`--proc temp="(temp-32)*5/9"`:: Convert from Fahrenheit to Celsius
`--proc name='remove("first").concat(remove("last"))'`:: Concatenate `first` and `last` fields and delete them
`--proc field2=null`:: Delete `field2`

Input fields are accessed by name (e.g. `field3=field1+field2`).

Processors have access to the following context variables and functions:

`date`:: Date parsing and formatting object.
Instance of Java https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html[SimpleDateFormat].

`number`:: Number parsing and formatting object.
Instance of Java https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html[DecimalFormat].

`faker`:: https://s01.oss.sonatype.org/service/local/repositories/releases/archive/net/datafaker/datafaker/2.3.1/datafaker-2.3.1-javadoc.jar/!/net/datafaker/Faker.html[Faker] object.

`redis`:: Redis commands object.
Instance of Lettuce https://www.lettuce.io/core/release/api/io/lettuce/core/api/sync/RedisCommands.html[RedisCommands].
The `replicate` command exposes 2 command objects named `source` and `target`.

`floatsToBytes`:: Convert an array of floats to a byte array so that the hash field can be indexed as vector (see https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/vectors/[Redis Vectors]).
+
For example if the field `vector` is an array of floats: `--proc embedding="#floatsToBytes(vector)"`

`geo`:: Convenience function for RediSearch geo-location strings in the form `longitude,latitude`.
+
For example with longitude and latitude fields `lon` and `lat`:  `--proc location="#geo(lon,lat)"`

.Processor example
[source,console,subs="verbatim,attributes"]
----
{app} file-import --proc epoch="#date.parse(mydate).getTime()" location="#geo(lon,lat)" name="#redis.hget('person1','lastName')" ...
----

.Faker processor example
[source,console]
----
include::{testdir}/file-import-process-faker[]
----

You can register your own variables using `--var`.

.Custom variable example
[source,console]
----
include::{testdir}/file-import-process-var[]
----

== Filtering

Filters allow you to exclude records that don't match a {link_spel} boolean expression.

For example this filter will only keep records where the `value` field is a series of digits:

[source,console,subs="verbatim,attributes"]
----
{app} file-import --filter "value matches '\\d+'" ...
----

