[[_snowflake_import]]
= Snowflake Import

The `snowflake-import` command uses a Snowflake `STREAM` object to track changes (CDC) to a table and read them into
a Redis data structure like `hash` or `json`. The Snowflake `STREAM` is created and managed by RIOTX. The user credentials
you provide must have the ability to create a stream in the database and schema specified by the fully qualified object
name.

.Side effects and limitations
* `SAMPLE_DATABASE.SAMPLE_SCHEMA.DATA_TABLE_changestream` will be created or replaced
* `SAMPLE_DATABASE.SAMPLE_SCHEMA.DATA_TABLE_temp` table will be created or replaced by selecting from the stream.
      RIOT-X reads data out of this table and imports into Redis.
* `riotx:offset:SAMPLE_DATABASE.SAMPLE_SCHEMA.DATA_TABLE_changestream` - this key will be stored in the destination
      Redis database and is used to track the stream offset. If RIOT-X fails in the middle of copying data from the stream
      when restarted it will resume copying data from this offset. Removing this offset key from Redis will result in
      RIOT-X creating recreating the stream at time "NOW". If `--snapshot-mode INITIAL` option is specified the stream
      will also include the initial table data plus changes going forward. If you do not want initial table data to
      be included specify `--snapshot-mode NEVER`
* snowflake-import currently works on tables and views


The basic usage is:

[source,console]
----
riotx snowflake-import [TABLE] [OPTIONS] [REDIS COMMAND...]
----

For the full usage, run:
[source,console]
----
riotx snowflake-import --help
----

.Example: CDC to Hashes
[source,console]
----
riotx snowflake-import \
      SAMPLE_DATABASE.SAMPLE_SCHEMA.DATA_TABLE \
      --snapshot-mode INITIAL # include initial table data  \
      --jdbc-url "jdbc:snowflake://abcdefg.abc12345.snowflakecomputing.com" \
      --jdbc-driver net.snowflake.client.jdbc.SnowflakeDriver \
      --jdbc-user databaseuser \
      --jdbc-pass databasepassword \
      --repeat 60s # sleep 60s after each cdc batch import and then repeat \
      hset \
      --keyspace datatable \
      --key data_id # column name to use as id
----

The command above imports CDC data from the Snowflake table `SAMPLE_DATABASE.SAMPLE_SCHEMA.DATA_TABLE` into Redis hashes in the keyspace `datatable`.

If you only need to do a one time import of data from Snowflake you can use the `db-import` command.
This command will read all of the rows output from your SQL query and will write them to Redis.
For more information see the link:https://redis.github.io/riot/#_db_import[db-import] command.

.Example: One-time Import
[source,console]
----
riotx db-import \
      "SELECT * FROM SAMPLE_DATABASE.SAMPLE_SCHEMA.DATA_TABLE" \
      --jdbc-url "jdbc:snowflake://abcdefg.abc12345.snowflakecomputing.com" \
      --jdbc-driver net.snowflake.client.jdbc.SnowflakeDriver \
      --jdbc-user databaseuser \
      --jdbc-pass databasepassword \
      hset \
      --keyspace datatable \
      --key data_id # column name to use as id
----

This command performs a one-time import from Snowflake using the `db-import` command.
