name: Build

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
          cache: gradle

      - name: Setup Snowflake credentials
        if: ${{ env.SNOWFLAKE_PRIVATE_KEY != '' }}
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" | base64 -d > ~/.ssh/snowflake_rsa_key.p8
          chmod 600 ~/.ssh/snowflake_rsa_key.p8
        env:
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

      - name: Build
        shell: bash
        run: ./gradlew build aggregateTestReports -S
        env:
          RIOT_JDBC_URL: ${{ secrets.SNOWFLAKE_JDBC_URL }}
          RIOT_JDBC_USER: ${{ secrets.SNOWFLAKE_JDBC_USER }}
          RIOT_JDBC_PASS: ${{ secrets.SNOWFLAKE_JDBC_PASS }}

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/aggregate-tests/

