name: Clone Releases
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Releases
        uses: redis-field-engineering/gha-clone-releases@main
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          src_repo: redis/riotx
          dest_repo: redis/riotx-dist
          copy_assets: true
