name: Clone Releases

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Releases
        uses: andrewthetechie/gha-clone-releases@v1
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          src_repo: redis-field-engineering/riotx
          dest_repo: redis-field-engineering/riotx-dist
          copy_assets: true
