name: EarlyAccess

on:
  push:
    branches: [ main ]

permissions:
  actions: write
  id-token: write
  contents: write

jobs:
  precheck:
    name: Precheck
    uses: redis-field-engineering/riotx/.github/workflows/step-precheck.yml@main
    secrets: inherit

  jlink:
    name: Jlink
    needs: [precheck]
    if: endsWith(${{ needs.precheck.outputs.version }}, '-SNAPSHOT')
    uses: redis-field-engineering/riotx/.github/workflows/step-jlink.yml@main
    with:
      project-version: ${{ needs.precheck.outputs.version }}
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

  release:
    name: Release
    needs: [precheck, jlink]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: plugins/riotx/build

      - name: Download repos
        uses: actions/download-artifact@v4
        with:
          name: repos
          path: build/repos/local/release

      - name: Download jlink
        uses: actions/download-artifact@v4
        with:
          name: jlink
          path: out/jreleaser/assemble/riotx-standalone/jlink

      - name: Release
        uses: jreleaser/release-action@v2
        with:
          version: early-access
          arguments: full-release
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_DOCKER_DEFAULT_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          JRELEASER_SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          JRELEASER_SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
          JRELEASER_GITHUB_PACKAGES_USERNAME: ${{ secrets.GIT_USER }}
          JRELEASER_GITHUB_PACKAGES_PASSWORD: ${{ secrets.GIT_ACCESS_TOKEN }}
          JRELEASER_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: riotx-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties