name: X-Precheck

on:
  workflow_call:
    outputs:
      version:
        description: version
        value: ${{ jobs.precheck.outputs.version }}

permissions:
  contents: read

jobs:
  precheck:
    name: Precheck
    if: github.repository == 'redis/riotx' && startsWith(github.event.head_commit.message, 'Releasing version') != true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version
        id: vars
        shell: bash
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT
