name: Trigger Early Access

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  earlyaccess:
    name: Trigger Early Access
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRO }}
          cache: gradle

      - name: Build
        run: ./gradlew -PreproducibleBuild=true build -S

      - name: Rename artifacts
        run: |
          mkdir early-access
          cp plugins/riotx/build/distributions/riotx-*-SNAPSHOT.zip early-access/riotx-early-access.zip

      - name: Release early-access artifacts
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: early-access
          repo_token: ${{ secrets.GIT_ACCESS_TOKEN }}
          prerelease: true
          title: RIOT-X Early-Access
          files: |
            early-access/*
